arch_network_type: dynamic_ensemble_pointwise_comparator
arch_network_cfg:
  auxiliary_head_num: 12
  arch_embedder_cfg: {emb_hid: 100, num_hid: 100, num_layers: 1, use_hid: true}
  compare_loss_type: margin_linear
  compare_margin: 0.1
  mlp_dropout: 0.1
  mlp_hiddens: []
  optimizer: {lr: 0.001, type: Adam}
  scheduler: null

batch_size: 512
choose_pair_criterion: random
compare: true
compare_threshold: 0.0
epochs: 200
pretrain_epochs: 200
max_compare_ratio: 4.0
low_fidelity_type: 
- one_shot
- grad_norm
- snip
- grasp
- flops
- fisher
- jacob_cov
- plain
- synflow
- relu_logdet
- relu
- latency
low_fidelity_normalize: true
